### ISSUE TITLE
server是否支持裁剪, 比如去掉docker/es/oss/mail, 只留核心服务,便于单机部署.

### ISSUE THREAD

**Issue by gemmi** [ymm-tech/gods-pen-server#4]
如题, 在团队内部私有部署, 访问量并不大, 没有docker/es/oss/mail/这些需求, 是否有开关把这些功能屏蔽掉?

**Comment by jy03078959** [comment]
可以自行适当修改下。团队目前还没有计划把这些功能做成配置可选的服务。
